---

- hosts: all
  become: true
  pre_tasks:
  - name: update_server
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: zabbix_server
  become: true
  tasks:
  - name: install zabbix repo
    apt:
      deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb

  - name: update the repo
    apt:
      update_cache: yes

  - name: install zabbix base packages
    apt:
      name:
      - zabbix-server-mysql
      - zabbix-frontend-php 
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent 

- hosts: zabbix_server
  become: true
  roles:
    - zabbix_mysql
    - zabbix_nginx
    - zabbix_settings


